version: '3.8'
services:
#  molfar-core:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - REDIS_HOST=redis
#      - QDRANT_HOST=qdrant
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#    depends_on:
#      - redis
#      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
